# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:$PATH
# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"
# Would you like to use another custom folder than $ZSH/custom?
ZSH_CUSTOM="$HOME/.zsh_custom"
ZSH_CUSTOM_CONFIG="$ZSH_CUSTOM/config"

for file in $ZSH_CUSTOM_CONFIG/*; do
  echo "Sourcing $file"
  source "$file"
done

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# source [NEEDS TO BE LAST LINE]
source $ZSH/oh-my-zsh.sh
